name = "ConvolutionalAnalysisOperatorLearning"
uuid = "3a526176-b9f4-11e9-0037-2fe9a5ca0081"
authors = ["David Hong <dahong@umich.edu>"]
version = "0.1.0"

[deps]
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"

[compat]
ImageFiltering = "0.6.2"
OffsetArrays = "0.11.0"
julia = "1.0"
